Repository Likelion-at-SMWU-13th/OnDongNae-Client, pull requests merged in 2025-08, with the labels that each got.

#6 Feat/#3/공통 모바일뷰 세팅
  src/index.css
  src/main.jsx
  src/styles/setViewport.js
Labels: ⚙️ Setting, 🍄 교은

#16 15 feat 메뉴 직접 입력
  src/components/common/BottomNav.jsx
  src/components/common/LargeLightOrangeButton.jsx
  src/components/common/Subtitle.jsx
  src/components/menuManagement/MenuForm.jsx
  src/components/menuManagement/MenuFormRow.jsx
  src/pages/MenuManualPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🍄 교은

#24 Feat/#23/소상공인 가게 설명
  src/components/common/BottomNav.jsx
  src/components/common/DoubleTitle.jsx
  src/components/description/Button.jsx
  src/components/description/Buttons.jsx
  src/components/description/DetailDescription.jsx
  src/components/description/InputTitle.jsx
  src/components/description/ShortDescription.jsx
  src/index.css
  src/pages/store/description/DescriptionPage.jsx
  src/pages/store/description/DetailEditPage.jsx
  src/pages/store/description/SummaryEditPage.jsx
  src/pages/store/signup/LoginPage.jsx
  src/pages/store/signup/StoreHomePage.jsx
  src/router.jsx
  src/styles/description/EditPage.styles.js
  src/styles/description/StoreDescriptionPage.styles.js
  src/styles/signup/StoreHomePage.styles.js
Labels: ✨ Feature, ⚽ 소연

#26 Feat/#25/회원가입 가게명 입력
  index.html
  src/pages/store/signup/SelectMarketPage.jsx
  src/pages/store/signup/StoreNamePage.jsx
  src/router.jsx
Labels: ✨ Feature, ⚽ 소연

#31 Feat/#21/소상공인 영업시간
  src/components/common/BottomNav.jsx
  src/components/common/SmallButtonContainer.jsx
  src/components/hours/HoursEditRow.jsx
  src/components/hours/HoursTable.jsx
  src/components/hours/TimePickerModal.jsx
  src/index.css
  src/pages/MenuAllergensFailPage.jsx
  src/pages/store/hours/HoursEditPage.jsx
  src/pages/store/hours/HoursPage.jsx
  src/router.jsx
  src/utils/pageedittime.js
Labels: ✨ Feature, 🍄 교은

#34 Feat/#32/환율 계산 화면
  src/assets/icon-circle-down-arrow.svg
  src/components/rates/ButtonCurrency.jsx
  src/components/rates/InputBoxConverted.jsx
  src/components/rates/InputBoxKr.jsx
  src/components/rates/RatesDescription.jsx
  src/components/signup/SelectButton.jsx
  src/locales/en/common.json
  src/locales/ja/common.json
  src/locales/zh/common.json
  src/pages/customer/map/MainMapPage.jsx
  src/pages/customer/map/dummyData.js
  src/pages/customer/rates/ExchangeRatePage.jsx
  src/pages/store/signup/LoginPage.jsx
  src/pages/store/signup/SelectMarketPage.jsx
  src/pages/store/signup/SignupAccountInfoPage.jsx
  src/pages/store/signup/SignupLoadingPage.jsx
  src/pages/store/signup/SignupUserInfoPage.jsx
  src/pages/store/signup/StoreAddressPage.jsx
  src/pages/store/signup/StoreCategoryMainPage.jsx
  src/pages/store/signup/StoreCategorySubPage.jsx
  src/pages/store/signup/StoreImagePage.jsx
  src/pages/store/signup/StoreKeywordPage1.jsx
  src/pages/store/signup/StoreKeywordPage2.jsx
  src/pages/store/signup/StoreNamePage.jsx
  src/pages/store/signup/StorePhonePage.jsx
  src/router.jsx
  src/styles/rates/ExchangeRatesPage.styles.js
Labels: ✨ Feature, ⚽ 소연

#41 Feat/#33/깃허브 꼬임 해결
  src/assets/icon-call.svg
  src/assets/icon-mapMarker.svg
  src/assets/icon-parking.svg
  src/assets/icon-restroom.svg
  src/assets/img-market.svg
  src/components/Overview/OverviewBottonScroll.jsx
  src/components/common/KakaoMapContainer.jsx
  src/components/course/CourseContent.jsx
  src/locales/en/common.json
  src/locales/ja/common.json
  src/locales/zh/common.json
  src/pages/customer/course/CoursePage.jsx
  src/pages/customer/overview/OverviewInfoPage1.jsx
  src/pages/customer/overview/OverviewInfoPage2.jsx
  src/pages/customer/overview/OverviewInfoPage3.jsx
  src/pages/customer/overview/OverviewInfoPage4.jsx
  src/pages/customer/overview/OverviewInfoPage5.jsx
  src/pages/customer/overview/OverviewPage.jsx
  src/router.jsx
Labels: 🍄 교은, 🐞 Fix

#44 Api/#42/회원가입 가게등록 연동
  package-lock.json
  package.json
  src/pages/customer/map/MainMapPage.jsx
  src/pages/customer/rates/ExchangeRatePage.jsx
  src/pages/store/description/DescriptionPage.jsx
  src/pages/store/description/DetailEditPage.jsx
  src/pages/store/description/SummaryEditPage.jsx
  src/pages/store/signup/LoginPage.jsx
  src/pages/store/signup/SelectMarketPage.jsx
  src/pages/store/signup/SignupAccountInfoPage.jsx
  src/pages/store/signup/SignupLoadingPage.jsx
  src/pages/store/signup/StoreCategoryMainPage.jsx
  src/pages/store/signup/StoreCategorySubPage.jsx
Labels: ⚽ 소연, 📬 API

#46 40 feat 메뉴 추출 저장 성분 분석
  src/components/menuManagement/AllergensEdit.jsx
  src/components/menuManagement/MenuCorrect.jsx
  src/components/menuManagement/MenuCorrectRow.jsx
  src/components/menuManagement/MenuEdit.jsx
  src/components/menuManagement/MenuSave.jsx
  src/components/menuManagement/RegisteredMenu.jsx
  src/pages/MenuUploadPage.jsx
  src/pages/MenuUploadPreviewPage.jsx
  src/pages/store/menu/MenuAllergensApplyPage.jsx
  src/pages/store/menu/MenuAllergensFailPage.jsx
  src/pages/store/menu/MenuAllergensLoadingPage.jsx
  src/pages/store/menu/MenuAllergensSuccessPage.jsx
  src/pages/store/menu/MenuCorrectPage.jsx
  src/pages/store/menu/MenuExtractFailPage.jsx
  src/pages/store/menu/MenuExtractLoadingPage.jsx
  src/pages/store/menu/MenuExtractSavePage.jsx
  src/pages/store/menu/MenuExtractSuccess.jsx
  src/pages/store/menu/MenuExtractSuccessPage.jsx
  src/pages/store/menu/MenuManualPage.jsx
  src/pages/store/menu/MenuPage.jsx
  src/pages/store/menu/MenuUploadPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🍄 교은

#59 Feat/외국인 코스 추천 UI 구현 및 연동
  src/components/course/CourseContent.jsx
  src/components/course/CourseOption.jsx
  src/locales/en/common.json
  src/locales/ja/common.json
  src/locales/zh/common.json
  src/pages/customer/course/CourseAI.jsx
  src/pages/customer/course/CourseDetailPage.jsx
  src/pages/customer/course/CourseFail.jsx
  src/pages/customer/course/CourseLoading.jsx
  src/pages/customer/course/CoursePage.jsx
  src/pages/customer/course/CourseResultPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🍄 교은, 📬 API

#61 Api/#57/소상공인 나의가게 연동
  src/assets/img-defaultStoreImg.png
  src/assets/img-defaultStoreImg.svg
  src/components/common/KakaoMapContainer.jsx
  src/components/description/LongDescription.jsx
  src/components/description/ShortDescription.jsx
  src/components/map/MapSection.jsx
  src/components/map/ScrollArea.jsx
  src/lib/authAxios.js
  src/pages/customer/map/MapStoresPage.jsx
  src/pages/customer/rates/ExchangeRatePage.jsx
  src/pages/store/mystore/MyStoreEditPage.jsx
  src/pages/store/mystore/MyStoreInfoPage.jsx
  src/pages/store/signup/LoginPage.jsx
  src/pages/store/signup/SignupAccountInfoPage.jsx
  src/styles/description/EditPage.styles.js
Labels: ⚽ 소연, 📬 API

#63 API/#12/소상공인 영업시간 연동
  src/components/hours/HoursTable.jsx
  src/components/menuManagement/Allergens.jsx
  src/components/menuManagement/AllergensEdit.jsx
  src/components/menuManagement/MenuForm.jsx
  src/pages/store/hours/HoursEditPage.jsx
  src/pages/store/menu/MenuAllergensSuccessPage.jsx
  src/pages/store/menu/MenuExtractSuccessPage.jsx
  src/pages/store/menu/MenuPage.jsx
  src/pages/store/menu/MenuUploadPage.jsx
  src/router.jsx
Labels: 🍄 교은, 📬 API

#64 Feat/#62/온보딩 페이지 구현
  src/assets/img-koru1.svg
  src/assets/img-koru2.svg
  src/assets/img-koru3.svg
  src/assets/img-koru4.svg
  src/assets/img-next.svg
  src/components/mystore/MenuItem.jsx
  src/components/onboarding/Footer.jsx
  src/components/onboarding/Header.jsx
  src/components/onboarding/Logo.jsx
  src/components/onboarding/SkipButton.jsx
  src/locales/en/common.json
  src/locales/ja/common.json
  src/locales/zh/common.json
  src/pages/onboarding/OnboardingPage1.jsx
  src/pages/onboarding/OnboardingPage2.jsx
  src/pages/onboarding/OnboardingPage3.jsx
  src/pages/onboarding/OnboardingPage4.jsx
  src/pages/onboarding/OnboardingPage5.jsx
  src/pages/onboarding/SelectLanguagePage.jsx
  src/pages/store/mystore/MyStorePage.jsx
  src/pages/store/signup/LoginPage.jsx
  src/router.jsx
Labels: ✨ Feature, ⚽ 소연

#66 Fix/#21/영업시간 수정 페이지 타임 피커 모달 디자인 수정
  src/components/hours/TimePickerModal.jsx
Labels: 🍄 교은, 🎨 Design

#82 Feat/#79/온보딩 첫번째 페이지 제작 및 시작페이지 변경
  src/assets/logo-onboardong.png
  src/pages/onboarding/OnboardingPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🍄 교은

#84 Design/#77/디자인 수정
  src/components/common/TermsModal.jsx
  src/components/signup/TermsAgreement.jsx
  src/components/signup/TermsContent.js
  src/pages/store/signup/SelectMarketPage.jsx
  src/pages/store/signup/SignupAccountInfoPage.jsx
  src/pages/store/signup/SignupCompletePage.jsx
  src/pages/store/signup/SignupTermsPage.jsx
  src/pages/store/signup/SignupUserInfoPage.jsx
  src/pages/store/signup/StoreAddressPage.jsx
  src/pages/store/signup/StoreCategoryMainPage.jsx
  src/pages/store/signup/StoreCategorySubPage.jsx
  src/pages/store/signup/StoreImagePage.jsx
  src/pages/store/signup/StoreKeywordPage1.jsx
  src/pages/store/signup/StoreKeywordPage2.jsx
  src/pages/store/signup/StoreNamePage.jsx
  src/pages/store/signup/StorePhonePage.jsx
  src/styles/common/SignupScroll.styles.js
  src/styles/description/EditPage.styles.js
  src/styles/signup/ProgressBar.styles.js
  src/styles/signup/SelectMarketPage.styles.js
  src/styles/signup/SignupAccountInfoPage.styles.js
  src/styles/signup/SignupTermsPage.styles.js
  src/styles/signup/SignupUserInfoPage.styles.js
  src/styles/signup/StoreAddressPage.styles.js
  src/styles/signup/StoreCategoryPage.styles.js
  src/styles/signup/StoreImagePage.styles.js
  src/styles/signup/StoreKeywordPage.styles.js
  src/styles/signup/StorePhonePage.styles.js
Labels: ⚽ 소연, 🎨 Design

#89 Design/#85/input 영역 모바일 깨짐 수정
  src/components/hours/HoursEditRow.jsx
  src/components/hours/HoursTable.jsx
  src/components/hours/TimePickerModal.jsx
  src/components/menuManagement/MenuFormRow.jsx
  src/pages/onboarding/OnboardingPage.jsx
Labels: 🍄 교은, 🎨 Design, 🐞 Fix

#93 design/#77/언어 선택 후 자동 페이지 변경
  src/pages/onboarding/SelectLanguagePage.jsx
Labels: ⚽ 소연, 🎨 Design
